FROM node:18-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
ENV NEXT_PUBLIC_API_URL http://localhost:8000

EXPOSE 3000

CMD ["npm", "run", "dev"]
