"""Initial schema

Revision ID: 4eb94ef6a0e0
Revises: 
Create Date: 2026-06-22 20:53:27.161230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb94ef6a0e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'complete', 'failed', name='assessment_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('toolkit_version', sa.String(), nullable=False),
    sa.Column('domain_11_applicable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_dataset_id'), 'assessments', ['dataset_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('cqi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('cqi_band', sa.String(), nullable=False),
    sa.Column('prs', sa.Integer(), nullable=False),
    sa.Column('prs_band', sa.String(), nullable=False),
    sa.Column('release_classification', sa.Enum('Open', 'Controlled', 'Restricted', name='release_class'), nullable=False),
    sa.Column('classification_justification', sa.String(), nullable=False),
    sa.Column('report_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='severity_level'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_assessment_id'), 'audit_logs', ['assessment_id'], unique=False)
    op.create_table('domain_scores',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('domain_number', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('not_applicable', sa.Boolean(), nullable=False),
    sa.Column('confidence_level', sa.Enum('High', 'Medium', 'Low', name='confidence_level'), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('evidence_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_domain_scores_assessment_id'), 'domain_scores', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_scores_assessment_id'), table_name='domain_scores')
    op.drop_table('domain_scores')
    op.drop_index(op.f('ix_audit_logs_assessment_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_assessments_dataset_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
